const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
const PRUDUCT_LIST_SUCCESS = "PRUDUCT_LIST_SUCCESS";
const PRUDUCT_LIST_FAIL = "PRUDUCT_LIST_FAIL";

export { PRODUCT_LIST_REQUEST, PRUDUCT_LIST_SUCCESS, PRUDUCT_LIST_FAIL };
